### ISSUE TITLE
Would be happy to share experiences in building KSP controllers

### ISSUE THREAD

**Issue by namero999** [Daniel-Wareham/kerbal-controller#1]
Hello! Just watched the video on YT, really nice build. I've read in the documentation that the first attempt was to communicate directly with the simulator. I've done that via a custom serial protocol and KRPC. It works both ways (sending commands and receiving data for screens and dials), but KRPC doesn't seem actively maintained, so I'm worried about its future. I was thinking that the best approach could be hybrid (krpc + keyboard emulation). Anyway, open to discuss for fun.

**Comment by Daniel-Wareham** [comment]
Thanks for the comment. I’ve never came across KPRC in my research, only simpit and kerbal serial IO. Maybe that could’ve worked, but I’m considering this project shelved now. To be honest how technically good the final product is wasn’t really the main goal, it was to go through the experience of solving problems and building projects with friends
